### ISSUE TITLE
Clarification needed: Purpose of finger_depth parameter in panda.yaml configuration

### ISSUE THREAD

**Issue by ghost** [ethz-asl/vgn#39]
Hi, 

i am trying to understand what is this parameter, i went through the franks' panda robot catalogues and moveit pkg but could not find any reference on this problem of mine. 

In the panda_grasp configuration YAML file, there's a parameter named finger_depth with a value of 0.05.what is the  purpose and impact of this parameter are not clear from the context. could some one help....

thanks  !!!

```
panda_grasp:
  base_frame_id: panda_link0
  tool0_frame_id: panda_link8
  T_tool0_tcp: {rotation: [0.000, 0.000, -0.382, 0.924], translation: [0.000, 0.000, 0.065]}
  finger_depth: 0.05
  max_opening_width: 0.08
  cam:
    frame_id: camera_depth_optical_frame
    topic_name: /camera/depth/image_rect_raw
    intrinsic:
      height: 480
      width: 848
      K: [423.189, 0.0, 423.336, 0.0, 423.18, 242.692, 0.0, 0.0, 1.0]
  scan_joints:
    - [0.010523236721068734, -1.4790833239639014, 0.10027132190633238, -2.416246868493765, 0.08994288870361117, 1.4022499498261343, 0.8516519819506339]
    - [-0.5204305512655648, -0.7962560020246003, 0.9121961832112832, -1.6720657872605567, 0.0914094145960278, 1.2810500415696036, 0.8710614908889162]
    - [0.03202341903301707, 0.45900370514601985, 0.0743635250858064, -0.8394780465249851, 0.01546591704007652, 0.7776030993991428, 0.8335337665490805]
    - [0.0927063864391347, -0.6268411712966925, -0.5511789947129442, -1.8378490985067266, 0.1656381993108548, 1.2387742138438755, 0.9008788375077649]
```
